# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "New Beta Build"
  lane :beta do
    changelog_from_git_commits(
      pretty: "- (%ae) %s",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
      match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
      merge_commit_filtering: "exclude_merges", # Optional, lets you filter out merge commits
      path: "../"
    )
    version_info = flutter_version(
      pubspec_location: "../pubspec.yaml",
    )
    puts version_info
    # Tests if the version code retrieved from the pubspec.yaml matches
    version_code = version_info["version_code"]
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    upload_to_play_store(
      track: 'beta',
      version_code: version_code,
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )

    # ...
  end

  desc "Deploy live version"
  lane :deploy do
    changelog_from_git_commits(
      pretty: "- (%ae) %s",# Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      date_format: "short",# Optional, lets you provide an additional date format to dates within the pretty-formatted string
      match_lightweight_tag: false,  # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
      merge_commit_filtering: "exclude_merges", # Optional, lets you filter out merge commits
      path: "../"
    )
    version_info = flutter_version(
      pubspec_location: "../pubspec.yaml",
    )
    puts version_info
    version_code = version_info["version_code"]
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      version_code: version_code,
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
