# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "New Beta Build"
  lane :beta do
    version_info = flutter_version(
      pubspec_location: "../pubspec.yaml",
    )
    puts version_info
    # Tests if the version code retrieved from the pubspec.yaml matches
    version_code = version_info["version_code"]
    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
    upload_to_play_store(track: 'beta', version_code: version_code)

    # ...
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    version_info = flutter_version(
      pubspec_location: "../pubspec.yaml",
    )
    puts version_info
    upload_to_play_store(track: 'beta', track_promote_to: 'production', version_code: version_code)
  end
end
