name: CI for windows

on: [push]	

jobs:	
  build:	

    runs-on: windows-2019	

    steps:	
    - uses: actions/checkout@v2	
    - uses: actions/checkout@v2	
      with:	
        repository: flutter/flutter	
        ref: master	
        fetch-depth: 0
    - name: Add Flutter tags
      # Add tags, which are also necessary for version checks to work.
      run: git fetch origin +refs/tags/*:refs/tags/*
      working-directory: ${{ github.workspace }}/flutter
    - name: Add Flutter to path	
      run: echo "$env:GITHUB_WORKSPACE\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Enable desktop support	
      run: flutter config --enable-windows-desktop	
    - name: Build example debug	
      run: |	
        flutter packages get	
        flutter build -v windows --debug	
      working-directory: ${{ github.workspace }}/trump_quotes
    - name: Build example release	
      run: |	
        flutter packages get	
        flutter build -v windows --release
        ls build
        ls build/windows || true